appointments/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.login_registration.urls', namespace='login_registration')),
    url(r'^task', include('apps.appointment_app.urls', namespace='task'))
]

apps/appointment_app/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.user, name = 'user'),
    url(r'^/new$', views.new, name = 'new'),
    url(r'^/(?P<id>\d+)/show$', views.show),
    url(r'^/(?P<id>\d+)/update$', views.update, name ='update'),
    url(r'^/(?P<id>\d+)/edit/$', views.edit),
    url(r'^/(?P<id>\d+)/destroy/$', views.destroy),
]

apps/login_registration/urls.py
from django.conf.urls import url
from . import views
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login$', views.login, name='login'),
    url(r'^register$', views.register, name='register'),
    url(r'^logout$', views.logout, name='logout'),
]

apps/appointment_app/models.py
from __future__ import unicode_literals
from ..login_registration.models import User
from django.db import models


class Task(models.Model):
    created_by = models.ForeignKey(User)
    date = models.CharField(max_length=10)
    time = models.TimeField()
    status = models.CharField(max_length=10, default='Pending')
    task = models.CharField(max_length=30)

apps/login_registration/models.py
from __future__ import unicode_literals
from django.core.exceptions import ObjectDoesNotExist
from django.db import models
import bcrypt, re

EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')

class UserManager(models.Manager):
    def validateReg(self, request):
        errors = self.validate_inputs(request)

        if len(errors) > 0:
            return (False, errors)

        # No errors, time to hash the pw
        pw_hash = bcrypt.hashpw(request.POST['password'].encode(), bcrypt.gensalt())

        # pw is hashed, time to create new user
        user = self.create(first_name=request.POST['first_name'], last_name=request.POST['last_name'], email=request.POST['email'], pw_hash=pw_hash, dob=request.POST['dob'])

        return (True, user)

    def validateLogin(self, request):
        try:
            user = User.objects.get(email=request.POST['email'])
            # The email matched a record in the database, now test passwords
            password = request.POST['password'].encode()
            if bcrypt.hashpw(password, user.pw_hash.encode()):
                return (True, user)

        except ObjectDoesNotExist:
            pass

        return (False, ["Email/password don't match."])

    def validate_inputs(self, request):
        errors = []
        if len(request.POST['first_name']) < 2 or len(request.POST['last_name']) < 2:
            errors.append("Please include a first and/or last name longer than two characters.")
        if not EMAIL_REGEX.match(request.POST['email']):
            errors.append("Please include a valid email.")
        if len(request.POST['password']) < 8 or request.POST['password'] != request.POST['confirm_pw']:
            errors.append("Passwords must match and be at least 8 characters.")
        return errors

class User(models.Model):
    first_name = models.CharField(max_length=45)
    last_name = models.CharField(max_length=45)
    email = models.CharField(max_length=45)
    pw_hash = models.CharField(max_length=255)
    dob = models.DateField()
    objects = UserManager()

apps/appointment_app/views.py
from django.shortcuts import render, redirect, reverse
from models import Task, User
from django.contrib import messages
import time, re

Date_regex = re.compile(r'^(19|20)\d\d([- /.])(0[1-9]|1[012])\2(0[1-9]|[12][0-9]|3[01])$')

# Functions here will delegate to the correct method based on the HTTP verb

def user(request):
    if request.method == "POST":
        return create(request)
    # Else it's a GET, send to index method to return HTML
    return index(request)

def users_w_id(request, id):
    if request.method == "POST":
        return update(request, id)
    return show(request, id)

# *************************************************************************

# GET /users
def index(request):
    # Retrieve all Tasks to display in template
    Tasks = Task.objects.all().order_by('time')
    user = User.objects.get(id=request.session['user'])
    date_now = time.strftime("%Y-%m-%d")

    context = {
        "tasks" : Tasks, "date_now" : date_now
    }
    return render(request, "appointment_app/index.html", context)

# POST /users
def create(request):
    if not Date_regex.match(request.POST['date']):
        messages.error(request, 'Fix your date')
        return redirect('/task')
    user = User.objects.get(id=request.session['user'])
    Task.objects.create(created_by=user, date=request.POST['date'], time=request.POST['time'], task=request.POST['task'])
    return redirect(reverse('task:user'))

# GET /users/new
def new(request):
    return render(request, 'appointment_app/new.html')

# GET /users/<id>
def show(request, id):
    task = Task.objects.get(id=id)

    return render(request, 'appointment_app/show.html', { 'Task' : Task })


# POST /task/<id>
def update(request, id):
    task = Task.objects.get(id=id)
    task.task = request.POST['task']
    task.date = request.POST['date']
    task.time = request.POST['time']
    task.status = request.POST['status']
    task.save()
    return redirect('/task')

# GET /users/<id>/edit
def edit(request, id):
    task = Task.objects.get(id=id)
    return render(request, 'appointment_app/edit.html', { 'Task' : task })

# POST /users/<id>/destroy
def destroy(request, id):
    Task.objects.get(id=id).delete()
    return redirect('/task')

apps/login_registration/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.contrib import messages
from .models import User

def index(request):
    return render(request, 'login_registration/index.html')

def login(request):
    result = User.objects.validateLogin(request)

    if result[0] == False:
        print_messages(request, result[1])
        return redirect(reverse('login_registration:index'))

    return log_user_in(request, result[1])

def register(request):
    result = User.objects.validateReg(request)

    if result[0] == False:
        print_messages(request, result[1])
        return redirect(reverse('login_registration:index'))

    return log_user_in(request, result[1])

def print_messages(request, message_list):
    for message in message_list:
        messages.add_message(request, messages.INFO, message)

def log_user_in(request, user):
    request.session['logged_in'] = True
    request.session['user'] = user.id
    return redirect('/task')

def logout(request):
    request.session.pop('user')
    return redirect(reverse('index'))

apps/appointment_app/templates/appointment_app/edit.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Edit product</title>
    <link rel="stylesheet" href="{% static 'appointment_app/css/styles.css' %}">
  </head>
  <body>
    <div class="wrapper">
      <form action='/task/{{ Task.id }}/update' method='post'>
      {% csrf_token %}
      <p>
        Task: <input type="text" name="task" value="{{Task.task}}">
      </p>
      <p>
        Date: <input type="text" name="date" value="{{Task.date}}">
      </p>
      <p>
        Time: <input type="time" name="time" value="{{Task.time}}">
      </p>
      <p>
        Status: <select type="text" name="status" value="{{Task.status}}">
          <option value="Pending">Pending</option>
          <option value="Missed">Missed</option>
          <option value="Done">Done</option>
      </p>
      <input type="submit" value="Update">
    </form>
      <a href="/task/{{ Task.id }}/">Show</a>
      <a href="/task">Back</a>
    </div>

  </body>
</html>

apps/appointment_app/templates/appointment_app/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Products</title>
    <link rel="stylesheet" href="{% static 'appointment_app/css/styles.css' %}">
  </head>
  <body>
    <h1>Here are your appointments for today {{date_now}}</h1>
    <table>
      <thead>
        <tr>
          <th>Tasks</th>
          <th>Time <a href="/task/index"></a></th>
          <th>Status</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        {% for task in tasks %}
        {% if task.date == date_now and task.status != 'Done' %}
        <tr>
          <td>{{task.task}}</td>
          <td>{{task.time}}</td>
          <td>{{task.status}}</td>
          <td>
            <a href="/task/{{task.id}}/edit/">Edit</a>
            <form action="/task/{{task.id}}/destroy/" method='post' class='delete'>
              {% csrf_token %}
              <input type="submit" value="Delete!">
            </form>
          </td>
        </tr>
        {% endif %}
        {% endfor %}
        {% for task in tasks %}
        {% if task.date == date_now and task.status == 'Done' %}
        <tr>
          <td>{{task.task}}</td>
          <td>{{task.time}}</td>
          <td>{{task.status}}</td>
          <td>

          </td>
        </tr>
        {% endif %}
        {% endfor %}
      </tbody>
    </table>
    <h1>Your Other Appointments</h1>
    <table>
      <thead>
        <tr>
          <th>Tasks</th>
          <th>Date</th>
          <th>Time</th>
        </tr>
      </thead>
      <tbody>
        {% for task in tasks %}
        <tr>
          <td>{{task.task}}</td>
          <td>{{task.date}}</td>
          <td>{{task.time}}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    <h2>Add a new task</h2>
    <form action="{% url 'task:user' %}" method='post'>
      {% csrf_token %}
      <p>
        Date: <input type="text" name="date" placeholder="yyyy-mm-dd">
      </p>
      <p>Time:
        <input type="time" name="time">
      </p>
      <p>
        Task: <input type="text" name="task" >
      </p>
      <input type="submit" value="Add">
    </form>
    {% if messages %}
    <ul class="alert-danger">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
  </body>
</html>

apps/appointment_app/templates/appointment_app/new.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Add new product</title>
    <link rel="stylesheet" href="{% static 'appointment_app/css/styles.css' %}">
  </head>
  <body>
    <h2>Add a new product</h2>
    <form action="/wish_list" method='post'>
      {% csrf_token %}
      item/Product: <input type="text" name="name">
      <input type="submit" value="Create">
    </form>
    <a href="/products">Go back</a>
  </body>
</html>

apps/appointment_app/templates/appointment_app/show.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Show Details</title>
    <link rel="stylesheet" href="{% static 'appointment_app/css/styles.css' %}">
  </head>
  <body>
    <h2>{{ task.name }}</h2>
    <p>users who added this to their wish list: </p>



  </body>
</html>

apps/login_registration/templates/login_registration/index.html
<html>
<!DOCTYPE html>
<head>
  <meta charset="utf-8">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- linking a css style sheet -->
    {% load staticfiles %}
  <link <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  <link rel="stylesheet" type="text/css" href="{% static 'login_registration/css/styles.css' %}">
  <meta charset="utf-8">
  <title>Login Registration</title>
  <link rel="stylesheet" href="{% static 'login_registration/css/styles.css' %}">
</head>
<body>
  <div class="wrapper">
    {% if messages %}
    <ul class="alert-danger">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
    <h2>Register</h2>
    <form action="{% url 'login_registration:register' %}" method='post'>
      {% csrf_token %}
      First Name <input type="text" name="first_name">
      Last Name <input type="text" name="last_name">
      Email <input type="email" name="email">
      Password <input type="password" name="password">
      Confirm Password <input type="password" name="confirm_pw">
      Date of Birth <input type="date" name="dob">
      <input type="submit" value="Register">
    </form>
    <h2>Login</h2>
    <form action="{% url 'login_registration:login' %}" method='post'>
      {% csrf_token %}
      Email <input type="email" name="email">
      Password <input type="password" name="password">
      <input type="submit" value="Login">
    </form>
  </div>
</body>
</html>